sudo: required
os:
# Temporary disable CI on linux untils the electron-slim-linux is date out.
# - linux
- osx
dist: trusty
osx_image: xcode9.2
language: node_js
node_js:
- 'node'
matrix:
  allow_failures:
cache:
- apt: true
- directories:
  - "node_modules"
  - "$HOME/.electron"
before_install:
- bash test/ci/before_install.sh
install:
- npm install -g codecov
- npm install -g electron-mocha
- npm install
- npm update
before_script:
# Generate a virtual framebuffer X server to collect Electron windows
- export DISPLAY=:99.0
- if [ $TRAVIS_OS_NAME == "linux" ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
script:
#- xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js
#- yarn run pack && xvfb-maybe node_modules/.bin/mocha test/e2e
# - if [ $TRAVIS_OS_NAME == "linux" ]; then xvfb-maybe npm run unit; else npm run unit; fi
- npm run unit
# - npm run e2e
- npm run build
deploy:
  provider: releases
  name: $TRAVIS_TAG
  api_key:
    secure: "PAPFtI8FpGjP2RvXKfUUNr8dBpAoLFukGtM+kxvBAzAyXIEH1IkINrDAPm4+TuyuareuG6xPvkpdktxhoDfbO62aAUs0/KioQxQfgmIv6xzvhuv/wfBpKezL/AffAoclMWwIl1JiqZwD6SKAVBU8A2teTskQrWnKIyRXkdxrEaBrmdZWuimc5H7Lb4MaMTO6Nmmm9eU2R2Gg2bOYhgAHBxUwGvxEacunl/VdJCFQdb70lQeREHqkPJ4SiXRWolCaEF33Y9UHpOAVUeup6ERzWri2LHn5cBVWFZ3DeEJr4MN+c7GpEFRWj3C1JsZ/e5mTNmvefldrFP386JW5zeyFGWjBiWgbV5au3hRVA/y76b+t39Xor39pBLz8RJhJs9TEwaBelminirFU/bk67CQ32KmxBHJNH8MgxGmgMBB8X/JgGOLpIrMgMTeErQY8XRMFBhzma4cbJ3DAl3JBV43759AZPL7h9+4NqCqBPPOrOehDNIe//bMVRi5Rd3tDtK3eC1F+NKobTq3xYYsKqktzzSkxJ/KC4oVL58ILnCND6EQ/MZtFphfvqnVTxS+Q2Mk2dMNjv0ZakrvDi/quGlgfionCPhgRbUiiYDnxEsVNJhkVfFiv2qk0clKJhQ10OarinTedLiqf7c2qT5Kj5shJXzSYyB+1eIC4KUttQgXZNLI="
  file_glob: true
  overwrite: true
  file:
  - build/*.dmg
  - build/*.deb
  - build/*.rpm
  skip_cleanup: true
  on:
    tags: true
after_success:
- codecov
branches:
addons:
  apt:
    packages:
    - xvfb
env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"