sudo: required
os:
- osx
dist: trusty
osx_image: xcode9.2
language: node_js
node_js:
- node
matrix:
  allow_failures: 
cache:
- apt: true
- directories:
  - node_modules
  - "$HOME/.electron"
before_install:
- bash test/ci/before_install.sh
install:
- npm install -g codecov
- npm install -g electron-mocha
- npm install
- npm update
before_script:
- export DISPLAY=:99.0
- if [ $TRAVIS_OS_NAME == "linux" ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
script:
- npm run mybuild
- ls build
- ls -R build
- pwd
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  file_glob: true
  overwrite: true
  file:
  - build/mac/*
  - build/*.dmg
  - build/*.deb
  - build/*.rpm
  - build/latest-mac.yml
  - build/*.blockmap
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: gU450OoPzRRyZfRoFVG9mr8MJoo8ceRT4kYRG9GidVMul49u0SHP7WWvIGUT4gl1k+BsuJ8WpXzDbmaTMvOR1g5QKYQxn185i+XQNEbcV7JbGIRkybucpXFWw8fqhhW7E3XFoXz7kSkS6HNbVk4FKCyaeqcVFiXQsMtTkKzL13XwdP8PgEGrHdmUSd2VoMzC5vS5cpkc4/BAIdvfh2LowWPdJzx/QiqUGKHKBjNvsK///nzhtKrwtVjuz6vw2PQTIzU5omHBE0lO7ANXqkb/Om1yaoqHxDWEZo7iOKa+v8ARsOaxeRt7XbzakR88tHNxwYdJEBRja8IChTc5wK1MfGtR3ZwDf56NNPr/5/HcLgk1LGEa6yN7VfNTqh0K4K+bbYGzsJPsFvy0NmjmzQbsWX402hWZuoVyTHatn4gcBwrVr/r26YHMNw3kwszQUY4vOjXGu4pVHaLP6cyOHtq35h8qP9WPUGHNA7oZfK1tNDgknObnNVlmkhiJVq8kA2zN1tRmkAbFMWBp1saIEdHbE31mgP01vBCy5+zRz74PDDdan/g0Ceo3vh2csRbtt9JCQxTMrejCbiJV8CKt6c89OEPvKRT2s+rjha3eAh6ssuqa0BE8SEDtny+hnnysXrue5rNu1Mnsd2qbReIgQC+XLVNE2yTaCNFoE8IKGcuk5ws=
after_success:
- codecov
branches: 
addons:
  apt:
    packages:
    - xvfb
env:
  global:
  - WINEDLLOVERRIDES="mscoree,mshtml="
  - WINEDEBUG="-all"
  - CSC_LINK : "MIIMeQIBAzCCDEAGCSqGSIb3DQEHAaCCDDEEggwtMIIMKTCCBo8GCSqGSIb3DQEHBqCCBoAwggZ8AgEAMIIGdQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIWL+GszkOg3MCAggAgIIGSJM7p1Iyd7ewCF7j1ypnqeCG8mHktmS8WrTUSXUrfeQFNzX0wRzDNreTDhElrTZnDpbAyGY+8RIiFNPdAAdj4xHGZe73nBnhk/oSRECi3vUWHVJ6eAeVn7zUCCoKbgcV3VG6g5GgviW3g5ti80Y9MUSM0wLvJBSDgGmgGreFL3WxJdNPzSNoGC3i0km7R2zU62PPq1iNp/S9lSVuz/I3NIlcMPyJ+UV29CBP0XKPkRvf7eHOrVXQyT6wqUT9CAC6B5xAWtxeuObs7eV2ZiScfWxQlgGAemfLHhEUGIdu+SrTGr2FK1EA+v1YC8stbtVz92srw5fN4pkJ5RDNBDVLNf3nsNMtfgvg/v0Ik3var+pzBW6mHpGt8sPxgdW0gvjCl+5hd2zhVrV273Mn/HmJBQZyPfpir0jgeueS/KwUBxAdaNxUdh2c1XkWNg0ZTrLLKLsCAHHiIGCZ1p19JmzwnuGNG8HvvyxpLsLuy9NefkHyodOafdkQ4l8Q1at6BBMJ9zXMp0VupmCOZb9Og9dQ9mWYk9b5VZyhICx4DHKdR0edfu8lQg4YEn7FSO+g7FO+RkHJ1IqLpSOkW8J61uqy9mCTYJzmFweN68SEBlkmcs4NlRc5K1IYcQJkMVq24KBa53CuRGyS3FzmwkMaSbV5IP4aBa7YblsbP2cRx4RtlEPZsV7goV9Q3Y3UjNN+JCe0QRAhChSeuGO/y6nwp8+dZimDelVv/+SLTT9ieJr8oZfD2vYJj65dxK+sh3r6OHH8t9LB5vRyxFmJcfbzhjhcrj+CO41JROy5sgUia7YSYMcc1x8Jc3qtbMrEfPx2BgadsqElbGOMgErV7qdjeZDRPynkE6bW7GceDVZ9lywuuN1PzEFAbeBWWDaS1VKdxev3cmSORisIUGdBQFj2e2pecpfHz/d4gTHJTIRvWbjP5uS/OrUCnDcOEKCEOt4ZilnTZWyonYgA1E/mSIkqh7xgZK8B88OhwopKxhHcGD8ehaj65C7hZuYfNf8i0HD5jGejwEVfFqKB864gai7WTTNl277mw4P9wgN7BOeMgee1m5Wgi5JhPeiKiLzoPdEW++DatKL5LpD0kEv8FkFnYaxXVv99GlgQ2UupjOlKO8jlXX/U7At5N0khDsp1RoUy0r8FsPLe/QjAJTxaFgOI66yXfdip+louzCad+VJ+dqjKCZTOhPaB9O02zyhNUG5jtxjc4nQBI+XXcpEGh2yHbNc4Oy0F4dC4nDfkZ2SRy96L/ALy+tLHe3LJo2wLXwfxIyfFhCfSJ3IpZr1StQVeKxelN4yBjjj4dcj/7FmpELzIgWEx+9QONBjWdbEmVv0P0mSo9MWeZ1/r95RrjrB3viQrtNEflPpJRUOoVi6wsNLQ0TeC4imdDGmFJN7Kc1xtxU0ilHiyL+rpCAsN9EBAp+MQsBXvsrx+G4iEjnct3AcJKhUwTgcoqKQU/B2APZg5aSaZB94k7TSVVz+955shh+/LkcvRR/1I9mZmXwlm2bDnucLqX+w6M+xcqvuxWNNR6qnmrC6rTp99khqkbrZw8S/E3DtB+I6bVDKPhbjU2fs6BzqCihmHacIFGbezr9bIK6l+CmV/+OS0MvMUXQNk0Pt7ZaLM0IJX1XJ8x4WxpPr1xYhjZKBEJWW968l53Z8NihDVqj9PC2AkOHyrZb8LoPJ5CE0+nqXFSAUEPXhbaJ5tliDyyHhXVzBm1CzbnYEDN7v3ZuPyU469ErLHx+xSs7OgIdP8oiKiUqQW99vOZlRSgs7CzVPMuKpLpGVThM8lJbsQgOA054BvI9Alz1sIOS5Xc7LWtEjdDsmmH986PMWHcZNeoJlZEHIJ+ichumUsz7xiShwP17Pjhbcb6nJEgw/fHv7rRbGjrrqvU2s/FgSOnTcOvjyJOCHPCIWAWXRLQ72kfi7MQ4U3990k2AAaLBpmt3EEcqRzcGS3jvF9Z7T1Pc6o6XowDvBf1mVx+WY9+g0Tm/hucpBxEUCa0q1hPUrLNB8GETpwl0JbNST9bS1DRigFVHZToXid07Jztkwoscxeoyb76/ooMW9H1DOYI/vsuYHgmBaeaU0PbQz1+tKOdX+BL3tmaFg+ajZgLtygwneYf5Qfn1mUV5KetxJqP91sXqgSwD8AqjE+yjCCBZIGCSqGSIb3DQEHAaCCBYMEggV/MIIFezCCBXcGCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcNAQwBAzAOBAizOIrAHHR4qwICCAAEggTIILYNF6vwMfRlj4fN9kIC2ezFOtTlyUrauyKHT6RHk/tlitb9hky0OmsnP0/5Uv1X1lh989UcFfFejLm1kv9d/hnwXgSWBnpCaliZ9Ws9DQkYtKYusmIWES4/XSGY5eQApw5AbCGhKngpnPECoBgbid+kpKJu8j6koquwt+BRSdRWQVEfSVeqdTiAq4SdxsN05zxYAXoE1sgHdK01qBSlg5hGiGZrTgihP8Nykg4kn1+IQGMK2ILws3BHv8uyuMX+xmkAVAgC+0ZQFc0C3AQ2SqV+WabxHSZHJXksRWLN8ok14ZYyeZVfxFpDZ/pQ7lBUN39CnxXo7K8XFJW6/sssLOe5jj++enzvu7dNBhS/8Lb5TOnwCpcPu9sXHkN2ZI9MRctjo+sj6Lt7cIqgw2DUC3rQEEBR5NNumri/qNFQer5z3FNBQKKcZb6IjePM0uGR8uJyrwoRT5uPpgK5q698/zeJC3v/kjeNIjq5TftKzucmNW5Fu1E1vEfUgHGS4iMfIXCRN+NW9JfE1aYhRaweMYwI8RXISxgf+tEqqoOfYk5nwTCTG8BcTGtKnkWzOVkrrIs+0YbGLp+2tScUhpDZgrrn+vTis+v+aEUjHQS/kIun6DIVHSphzu9RYZqNuaemvd4i5XRRlXoQlJ5UDAQ8I0Wq53oFh+YymYemRT+Sm9BkymbsY/CLrx3vAyxaD5DeQpMA1PdLyp9vFfzGNKJnflg2fXHmsZzT8OkFvDUoeIr6CuYMvmlFCxgoyd/H0av5L6DgwO237374DlL5Uk1BIAaW12HpzC6TlKzEXTobMK9+m+ff1Gtv8u4Zx/S7Vlq1Ep7Nf2NZYTx/43KYe9kXqyvhbYK3ulA50OW+krYZSx7I+/EH2nLw/iTFFwPbvwgAXlptb5ydeMczmDpnrbYSlniZvOWPTU7Y9DlPn6Btl21kzulTJfGNr852qfP5VnfaQBgzbqOYr+op8VJbycSC/3yXHQ2l1gcsjGLZXWHixw6jjRUS5v+NIcD5eTFjskSpDPt5UaJmN+PJMjgWRnBro7UvbezKlp1ndRI6yzSHr2YMUCCBlQe3rCHAyTVc3iVsxeFbBfM43Au6MTOOZTYjq1sTSBj8OX41jSPyj2AWm+K/TO8BiRczwcs5vRsiTJ28GcaBSgZZUIIcLd+INTq032IzoIce9tmgFyoZHH7puxpK4e/Rn06m04Yd66FtHtrIiil0bDfn3sC9owDCtvfN3k5vIjZB6jpfoeTdVdyd7aeNOiYynjQ7sI2ZoZvTZWddx9kZOF4EJCZ3IIqgpCbH1eLYArycOf9ltj+ZDNSV6pTiSFxKUpmLyhLVpOQBCVOAcvVgr7LljEJunRBdRCRPeJwXQBBv58bwQRw36RmgMx477TqLstghCHWD7O+jngiFNDoGnk8TAJSodO8eSyYnm+E8Dr2i768vwP6JII27+mb2lrb6wARSPlu+29olC70mdORgnaxxej3wiWHEIyKmTWyaEvsV1VcJTtV6/rIx1+I8So76y+44CTturOCg6WlMKTbAw7d/Q9UWjX/+wTumFqiuT3pU9NdBvHH7QEM0J+cbFRQqQvMHUlwoFnRE2YFu310qfvttZuYSQ1ZZ923oueW8tUELhkpgMXYwTwYJKoZIhvcNAQkUMUIeQABNAGEAYwAgAEQAZQB2AGUAbABvAHAAZQByADoAIABMAGkAbgBnACAAeQB5ACAAKABMAGkAbgBnACAAeQB5ACkwIwYJKoZIhvcNAQkVMRYEFDZTvzidclxBOY7kdGzrgbKdGreRMDAwITAJBgUrDgMCGgUABBSyfsccywTyCSFsSEL6zHA0MAnUCgQIEt8VyIWV5LoCAQE="
  - CSC_KEY_PASSWORD : "Xindong123"
