sudo: required
os:
# Temporary disable CI on linux untils the electron-slim-linux is date out.
# - linux
- osx
dist: trusty
osx_image: xcode9.2
language: node_js
node_js:
- 'node'
matrix:
  allow_failures:
cache:
- apt: true
- directories:
  - "node_modules"
  - "$HOME/.electron"
before_install:
- bash test/ci/before_install.sh
install:
- npm install -g codecov
- npm install -g electron-mocha
- npm install
- npm update
before_script:
# Generate a virtual framebuffer X server to collect Electron windows
- export DISPLAY=:99.0
- if [ $TRAVIS_OS_NAME == "linux" ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
script:
#- xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js
#- yarn run pack && xvfb-maybe node_modules/.bin/mocha test/e2e
# - if [ $TRAVIS_OS_NAME == "linux" ]; then xvfb-maybe npm run unit; else npm run unit; fi
- npm run unit
# - npm run e2e
- npm run build
deploy:
  provider: releases
  name: $TRAVIS_TAG
  file_glob: true
  overwrite: true
  github-token: 182981a70b41b783be24701519f9020fd276bc14
  file:
  - build/*.dmg
  - build/*.deb
  - build/*.rpm
  skip_cleanup: true
  on:
    tags: true
after_success:
- codecov
branches:
addons:
  apt:
    packages:
    - xvfb
env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"