sudo: required
os:
- osx
dist: trusty
osx_image: xcode9.2
language: node_js
node_js:
- node
matrix:
  allow_failures: 
cache:
- apt: true
- directories:
  - node_modules
  - "$HOME/.electron"
before_install:

install:
- npm install codecov
- npm install electron-mocha
- npm install
- npm update
before_script:
- export DISPLAY=:99.0
- if [ $TRAVIS_OS_NAME == "linux" ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
script:
- npm run build
- ls build
- ls -R build
- npm view electron-updater
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  file_glob: true
  overwrite: true
  file:
  - build/*.node
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: gU450OoPzRRyZfRoFVG9mr8MJoo8ceRT4kYRG9GidVMul49u0SHP7WWvIGUT4gl1k+BsuJ8WpXzDbmaTMvOR1g5QKYQxn185i+XQNEbcV7JbGIRkybucpXFWw8fqhhW7E3XFoXz7kSkS6HNbVk4FKCyaeqcVFiXQsMtTkKzL13XwdP8PgEGrHdmUSd2VoMzC5vS5cpkc4/BAIdvfh2LowWPdJzx/QiqUGKHKBjNvsK///nzhtKrwtVjuz6vw2PQTIzU5omHBE0lO7ANXqkb/Om1yaoqHxDWEZo7iOKa+v8ARsOaxeRt7XbzakR88tHNxwYdJEBRja8IChTc5wK1MfGtR3ZwDf56NNPr/5/HcLgk1LGEa6yN7VfNTqh0K4K+bbYGzsJPsFvy0NmjmzQbsWX402hWZuoVyTHatn4gcBwrVr/r26YHMNw3kwszQUY4vOjXGu4pVHaLP6cyOHtq35h8qP9WPUGHNA7oZfK1tNDgknObnNVlmkhiJVq8kA2zN1tRmkAbFMWBp1saIEdHbE31mgP01vBCy5+zRz74PDDdan/g0Ceo3vh2csRbtt9JCQxTMrejCbiJV8CKt6c89OEPvKRT2s+rjha3eAh6ssuqa0BE8SEDtny+hnnysXrue5rNu1Mnsd2qbReIgQC+XLVNE2yTaCNFoE8IKGcuk5ws=
  after_success:
  - codecov
branches: 
addons:
  apt:
    packages:
    - xvfb
env:
  global:
  - WINEDLLOVERRIDES="mscoree,mshtml="
  - WINEDEBUG="-all"
